/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaLogin.java
 *
 * Created on 27/10/2011, 00:14:19
 */

package projetolattes.telas;


import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import projetolattes.bd.Transacao;
import projetolattes.beans.Usuario;
import projetolattes.util.Main;
import projetolattes.util.Monitoramento;
import projetolattes.util.Sessao;

/**
 * Frame da tela Login
 * @author Thatiany Lima e Aline Gonçalves
 */
public class TelaLogin extends javax.swing.JInternalFrame {

    private static Logger log = Logger.getLogger(TelaLogin.class.getName());

    /** 
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        //Altera o ícone do frame interno da Tela de Login
        initComponents();
        try{
            Icon icon = new ImageIcon("src/projetolattes/imagens/lock_edit.png");
            setFrameIcon(icon);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, Main.recursos.getString("txt.erro.lattes"),0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSenha = new javax.swing.JPasswordField();
        txtMatricula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnIdiomaIngles = new javax.swing.JToggleButton();
        btnIdiomaPortugues = new javax.swing.JButton();
        btnIdiomaEspanhol = new javax.swing.JToggleButton();

        setTitle("Login");
        setAlignmentX(5.0F);
        setAlignmentY(5.0F);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText(Main.recursos.getString("txtMatricula.tela.login"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText(Main.recursos.getString("txtSenha.tela.login"));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/cadeado.gif"))); // NOI18N
        btnLogin.setText(Main.recursos.getString("btnLogin.tela.login"));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/Cancel.png"))); // NOI18N
        btnCancelar.setText(Main.recursos.getString("btnCancelar.tela.login"));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText(Main.recursos.getString("rotuloIdioma.tela.principal"));

        btnIdiomaIngles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/eua.jpg"))); // NOI18N
        btnIdiomaIngles.setText(Main.recursos.getString("btnIngles.tela.principal"));
        btnIdiomaIngles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIdiomaInglesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIdiomaInglesMouseExited(evt);
            }
        });
        btnIdiomaIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdiomaInglesActionPerformed(evt);
            }
        });

        btnIdiomaPortugues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/br.jpg"))); // NOI18N
        btnIdiomaPortugues.setText(Main.recursos.getString("btnPortugues.tela.principal"));
        btnIdiomaPortugues.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIdiomaPortuguesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIdiomaPortuguesMouseExited(evt);
            }
        });
        btnIdiomaPortugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdiomaPortuguesActionPerformed(evt);
            }
        });

        btnIdiomaEspanhol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/es.jpg"))); // NOI18N
        btnIdiomaEspanhol.setText(Main.recursos.getString("btnEspanhol.tela.principal"));
        btnIdiomaEspanhol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIdiomaEspanholMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIdiomaEspanholMouseExited(evt);
            }
        });
        btnIdiomaEspanhol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdiomaEspanholActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIdiomaIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIdiomaPortugues, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIdiomaEspanhol, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIdiomaIngles)
                    .addComponent(jLabel3)
                    .addComponent(btnIdiomaPortugues)
                    .addComponent(btnIdiomaEspanhol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnLogin))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    {
//GEN-FIRST:event_jButton1ActionPerformed
        
                                            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * Trata o evento do botão Login
    * @param evt O evento
    */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try{
            Transacao.abrir();
            Usuario u = new Usuario();

            u.setMatricula(txtMatricula.getText());
            u.setSenha(txtSenha.getText());

            // Tenta setar o usuario na sessão (login)
            Sessao.setUsuario(u);

            log.info(Main.recursos.getString("log.login.login1") + " " +  txtMatricula.getText()  + " " +  Main.recursos.getString("log.login.login2"));

            // Inicia o monitoramento de curriculos com intervalo de tempo de 7 dias
            new Monitoramento().start();
        }
        catch(Exception e){
            e.getMessage();
            JOptionPane.showMessageDialog(null,Main.recursos.getString("txt.erro.login") + e.getMessage(),      Main.recursos.getString("txt.erro2.principal"),   JOptionPane.INFORMATION_MESSAGE);
            log.warning(Main.recursos.getString("log.login.erroLogin") + e.getMessage());
            txtMatricula.setText("");
            txtSenha.setText("");
            return;
        }


        TelaPrincipal.enableButtons(true);
        TelaPrincipal.enableMenus(true);
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * Método para tratar envento do tipo ActionEvent. Tipo de evento gerado quanto se clica em um botão.
     * @param evt Evento que foi gerado pelo botão cancelar
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Sai do sistema
        log.info(Main.recursos.getString("log.login.finalizado"));
         Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

     /**
     * Trata o evento do botão idioma Inglês
     * @param evt O evento
     */
    private void btnIdiomaInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdiomaInglesActionPerformed
        //fecha a janela e abre o progrma novamento com o idioma inglês
        dispose();
        Main.mudarIdioma("Ingles");
    }//GEN-LAST:event_btnIdiomaInglesActionPerformed

    /**
     * Trata o evento do botão idioma Português
     * @param evt O evento
     */
    private void btnIdiomaPortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdiomaPortuguesActionPerformed
        //fecha a janela e abre o progrma novamento com o idioma português
        dispose();
        Main.mudarIdioma("Portugues");
    }//GEN-LAST:event_btnIdiomaPortuguesActionPerformed

      /**
     * Trata o evento de mouse no botão idioma Inglês
     * @param evt O evento
     */
    private void btnIdiomaInglesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaInglesMouseEntered
         btnIdiomaIngles.setBorderPainted(false);
    }//GEN-LAST:event_btnIdiomaInglesMouseEntered

    /**
     * Trata o evento de mouse no botão idioma Inglês
     * @param evt O evento
     */
    private void btnIdiomaInglesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaInglesMouseExited
         btnIdiomaIngles.setBorderPainted(true);
    }//GEN-LAST:event_btnIdiomaInglesMouseExited

    /**
     * Trata o evento de mouse no botão idioma Português
     * @param evt O evento
     */
    private void btnIdiomaPortuguesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaPortuguesMouseEntered
        btnIdiomaPortugues.setBorderPainted(true);
    }//GEN-LAST:event_btnIdiomaPortuguesMouseEntered

    /**
     * Trata o evento de mouse no botão idioma Português
     * @param evt O evento
     */
    private void btnIdiomaPortuguesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaPortuguesMouseExited
         btnIdiomaPortugues.setBorderPainted(true);
    }//GEN-LAST:event_btnIdiomaPortuguesMouseExited

    /**
     * Trata o evento do botão idioma Espanhol
     * @param evt O evento
     */
    private void btnIdiomaEspanholActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdiomaEspanholActionPerformed
       //fecha a janela e abre o progrma novamento com o idioma espanhol
        dispose();
        Main.mudarIdioma("Espanhol");
}//GEN-LAST:event_btnIdiomaEspanholActionPerformed

    /**
     * Trata o evento de mouse no botão idioma Espanhol
     * @param evt O evento
     */
    private void btnIdiomaEspanholMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaEspanholMouseEntered
       btnIdiomaEspanhol.setBorderPainted(true);
}//GEN-LAST:event_btnIdiomaEspanholMouseEntered

    /**
     * Trata o evento de mouse no botão idioma Espanhol
     * @param evt O evento
     */
    private void btnIdiomaEspanholMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIdiomaEspanholMouseExited
         btnIdiomaEspanhol.setBorderPainted(false);
    }//GEN-LAST:event_btnIdiomaEspanholMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JToggleButton btnIdiomaEspanhol;
    private javax.swing.JToggleButton btnIdiomaIngles;
    private javax.swing.JButton btnIdiomaPortugues;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
