/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaRelatorio.java
 *
 * Created on 13/11/2011, 15:36:01
 */

package projetolattes.telas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import projetolattes.bd.Consultas;
import projetolattes.bd.Transacao;
import projetolattes.util.Main;

/**
 * Frame interno da Tela de Relatorio
 * @author Thatiany Lima e Aline Gonçalves
 */
public class TelaRelatorio extends javax.swing.JInternalFrame {

     private static Logger log = Logger.getLogger(TelaRelatorio.class.getName());

    /** 
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
       //Altera o ícone do frame interno da Tela de Relatórios
        try{
            Icon icon = new ImageIcon("src/projetolattes/imagens/professor.png");
            setFrameIcon(icon);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e, Main.recursos.getString("txt.erro.lattes"),0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnEmitirRelatorioPorProf = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        relProfessor = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        btnCancelarRelPorProf = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnEmitirRelatorioGeral = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        qntTrab = new javax.swing.JLabel();
        qntLivrosCap = new javax.swing.JLabel();
        qntArtigos = new javax.swing.JLabel();
        qntTotalProd = new javax.swing.JLabel();
        qntOriGraduacao = new javax.swing.JLabel();
        qntOriEspecializacao = new javax.swing.JLabel();
        qntOriMestrado = new javax.swing.JLabel();
        qntOriDoutorado = new javax.swing.JLabel();
        qntTotalOrientacao = new javax.swing.JLabel();
        qntExaminadora = new javax.swing.JLabel();
        qntJulgadora = new javax.swing.JLabel();
        qntTotalBanca = new javax.swing.JLabel();
        btnCancelarRelGeral = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle(Main.recursos.getString("titulo.tela.relatorio"));
        setAutoscrolls(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEmitirRelatorioPorProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/grafico.png"))); // NOI18N
        btnEmitirRelatorioPorProf.setText(Main.recursos.getString("btnEmitirRel.tela.relatorio"));
        btnEmitirRelatorioPorProf.setToolTipText("Emiti relatório por professor");
        btnEmitirRelatorioPorProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirRelatorioPorProfActionPerformed(evt);
            }
        });

        relProfessor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        relProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Professor", "T", "L/C", "A", "O G", "O  E", "O  M", "O  D", "B J", "B  E", "Total"
            }
        ));
        jScrollPane1.setViewportView(relProfessor);
        relProfessor.getColumnModel().getColumn(0).setPreferredWidth(500);
        relProfessor.getColumnModel().getColumn(1).setPreferredWidth(50);
        relProfessor.getColumnModel().getColumn(2).setPreferredWidth(60);
        relProfessor.getColumnModel().getColumn(3).setPreferredWidth(50);
        relProfessor.getColumnModel().getColumn(4).setPreferredWidth(60);
        relProfessor.getColumnModel().getColumn(5).setPreferredWidth(60);
        relProfessor.getColumnModel().getColumn(6).setPreferredWidth(60);
        relProfessor.getColumnModel().getColumn(7).setPreferredWidth(60);
        relProfessor.getColumnModel().getColumn(8).setPreferredWidth(60);
        relProfessor.getColumnModel().getColumn(9).setPreferredWidth(90);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Legenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel23.setText("T :");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel30.setText("B E :");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel31.setText(Main.recursos.getString("txtOG.tela.relatorio"));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel32.setText(Main.recursos.getString("txtArtigos.tela.cadastro"));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel33.setText(Main.recursos.getString("txtLC.tela.cadastro"));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel34.setText(Main.recursos.getString("txtTCPA.tela.cadastro"));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel36.setText("L/C :");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel37.setText("A :");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel38.setText("O G :");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel39.setText("O E :");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel40.setText("O M :");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel41.setText("O D :");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel42.setText("B J :");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel45.setText(Main.recursos.getString("txtOE.tela.relatorio"));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel46.setText(Main.recursos.getString("txtOM.tela.relatorio"));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel47.setText(Main.recursos.getString("txtOD.tela.relatorio"));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel49.setText(Main.recursos.getString("txtBE.tela.cadastro"));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel50.setText(Main.recursos.getString("txtBJ.tela.cadastro"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel37)
                                .addComponent(jLabel36))))
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel30)
                    .addComponent(jLabel40))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel50)
                            .addComponent(jLabel49))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel34)
                    .addComponent(jLabel40)
                    .addComponent(jLabel46))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel33)
                    .addComponent(jLabel41)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel32)
                    .addComponent(jLabel42)
                    .addComponent(jLabel49))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel31)
                    .addComponent(jLabel50)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel45))
                .addContainerGap())
        );

        btnCancelarRelPorProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/Cancel.png"))); // NOI18N
        btnCancelarRelPorProf.setText(Main.recursos.getString("btnCancelar.tela.relatorio"));
        btnCancelarRelPorProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRelPorProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(btnEmitirRelatorioPorProf)
                        .addGap(75, 75, 75)
                        .addComponent(btnCancelarRelPorProf)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmitirRelatorioPorProf)
                            .addComponent(btnCancelarRelPorProf)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab(Main.recursos.getString("tituloGuia1.tela.relatorio"), jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEmitirRelatorioGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/grafico.png"))); // NOI18N
        btnEmitirRelatorioGeral.setText(Main.recursos.getString("btnEmitirRel.tela.relatorio"));
        btnEmitirRelatorioGeral.setToolTipText("Emiti relatório por professor");
        btnEmitirRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirRelatorioGeralActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText(Main.recursos.getString("txtProducoes.tela.relatorio"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText(Main.recursos.getString("txtBanca.tela.cadastro"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText(Main.recursos.getString("txtOrientacoes.tela.cadastro"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText(Main.recursos.getString("txtTrabalhos.tela.relatorio"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText(Main.recursos.getString("txtLC.tela.cadastro"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText(Main.recursos.getString("txtArtigos.tela.cadastro"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText(Main.recursos.getString("txtTotal.tela.relatorio"));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText(Main.recursos.getString("txtJulgadoras.tela.relatorio"));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText(Main.recursos.getString("txtExaminadoras.tela.relatorio"));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText(Main.recursos.getString("txtTotal.tela.relatorio"));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setText(Main.recursos.getString("txtOG.tela.relatorio"));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText(Main.recursos.getString("txtOE.tela.relatorio"));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setText(Main.recursos.getString("txtOM.tela.relatorio"));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setText(Main.recursos.getString("txtOD.tela.relatorio"));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel19.setForeground(new java.awt.Color(153, 0, 0));
        jLabel19.setText(Main.recursos.getString("txtTotal.tela.relatorio"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Legenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel20.setText(Main.recursos.getString("txtTrabalhos.tela.relatorio"));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel27.setText(Main.recursos.getString("txtTCPA.tela.cadastro"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel27))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        qntTotalProd.setForeground(new java.awt.Color(153, 0, 0));

        qntTotalOrientacao.setForeground(new java.awt.Color(153, 0, 0));

        qntTotalBanca.setForeground(new java.awt.Color(153, 0, 0));

        btnCancelarRelGeral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetolattes/imagens/Cancel.png"))); // NOI18N
        btnCancelarRelGeral.setText(Main.recursos.getString("btnCancelar.tela.relatorio"));
        btnCancelarRelGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRelGeralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(qntTrab, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(qntLivrosCap, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(qntArtigos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(qntTotalProd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(428, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel14))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(qntExaminadora, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(qntJulgadora, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(qntTotalBanca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(525, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel15)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel16)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel17)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel18)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(qntOriGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(qntOriEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)
                                .addComponent(qntOriMestrado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                                .addComponent(qntOriDoutorado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(qntTotalOrientacao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))))
                .addGap(224, 224, 224))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(824, Short.MAX_VALUE)
                .addComponent(btnEmitirRelatorioGeral)
                .addGap(42, 42, 42)
                .addComponent(btnCancelarRelGeral)
                .addGap(68, 68, 68))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(930, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(qntTrab, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntLivrosCap, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qntArtigos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntTotalProd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(qntOriMestrado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntTotalOrientacao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntOriDoutorado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qntOriEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntOriGraduacao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addGap(5, 5, 5)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(qntExaminadora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qntJulgadora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qntTotalBanca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmitirRelatorioGeral)
                            .addComponent(btnCancelarRelGeral))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );

        jTabbedPane1.addTab(Main.recursos.getString("tituloGuia2.tela.relatorio"), jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para tratar envento do tipo ActionEvent. Tipo de evento gerado quanto se clica em um botão.
     * @param evt Evento que foi gerado pelo botão cancelar Relatorio Por Professor
     */
    private void btnCancelarRelPorProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRelPorProfActionPerformed
        log.info(Main.recursos.getString("log.cancelar.relatorio"));
        //fecha a janela interna de relatorio
        dispose();
}//GEN-LAST:event_btnCancelarRelPorProfActionPerformed

    /**
     * Método para tratar envento do tipo ActionEvent. Tipo de evento gerado quanto se clica em um botão.
     * @param evt Evento que foi gerado pelo botão cancelar relatorio Geral
     */
    private void btnCancelarRelGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRelGeralActionPerformed
        log.info(Main.recursos.getString("log.cancelar.relatorio"));
        // fecla a janela interna de relatorio
        dispose();
        
}//GEN-LAST:event_btnCancelarRelGeralActionPerformed

    /**
     * Método para tratar envento do tipo ActionEvent. Tipo de evento gerado quanto se clica em um botão.
     * @param evt Evento que foi gerado pelo botão emitir relatorio por professor
     */
    private void btnEmitirRelatorioPorProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirRelatorioPorProfActionPerformed
         try {
            Transacao.abrir();
            log.info(Main.recursos.getString("log.iniciar.relatorio"));
            relProfessor.setModel(new javax.swing.table.DefaultTableModel(
                    Consultas.relatorioPorProfessor(),
                    new String[]{"Professor", "T", "L/C", "A", "O G", "O  E", "O  M", "O  D", "B J", "B  E", "Total"
            }));
            relProfessor.repaint();

            String[] totais = Consultas.relatorioGeral();

            // Atualiza os rótulos com os valores da consulta
            qntOriGraduacao.setText(totais[0]);
            qntOriEspecializacao.setText(totais[1]);
            qntOriMestrado.setText(totais[2]);
            qntOriDoutorado.setText(totais[3]);
            qntTotalOrientacao.setText(Integer.toString(Integer.parseInt(totais[0]) + Integer.parseInt(totais[1]) +
                    Integer.parseInt(totais[2]) + Integer.parseInt(totais[3])));

            qntTrab.setText(totais[4]);
            qntArtigos.setText(totais[5]);
            qntLivrosCap.setText(totais[6]);
            qntTotalProd.setText(Integer.toString(Integer.parseInt(totais[4]) + Integer.parseInt(totais[5]) + Integer.parseInt(totais[6])));

            qntExaminadora.setText(totais[7]);
            qntJulgadora.setText(totais[8]);
            qntTotalBanca.setText(Integer.toString(Integer.parseInt(totais[7]) + Integer.parseInt(totais[8])));

            log.info(Main.recursos.getString("log.emitir.relatorio"));
        } catch (Exception ex) {
            log.warning(Main.recursos.getString("log.erro.relatorio"));
            Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEmitirRelatorioPorProfActionPerformed

        /**
     * Método para tratar envento do tipo ActionEvent. Tipo de evento gerado quanto se clica em um botão.
     * @param evt Evento que foi gerado pelo botão emitir relatorio geral
     */
    private void btnEmitirRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirRelatorioGeralActionPerformed
        try {
            Transacao.abrir();
            log.info(Main.recursos.getString("log.iniciar.relatorio"));
            relProfessor.setModel(new javax.swing.table.DefaultTableModel(
                    Consultas.relatorioPorProfessor(),
                    new String[]{"Professor", "T", "L/C", "A", "O G", "O  E", "O  M", "O  D", "B J", "B  E", "Total"
            }));
            relProfessor.repaint();

            String[] totais = Consultas.relatorioGeral();

            // Atualiza os rótulos com os valores da consulta
            qntOriGraduacao.setText(totais[0]);
            qntOriEspecializacao.setText(totais[1]);
            qntOriMestrado.setText(totais[2]);
            qntOriDoutorado.setText(totais[3]);
            qntTotalOrientacao.setText(Integer.toString(Integer.parseInt(totais[0]) + Integer.parseInt(totais[1]) +
                    Integer.parseInt(totais[2]) + Integer.parseInt(totais[3])));

            qntTrab.setText(totais[4]);
            qntArtigos.setText(totais[5]);
            qntLivrosCap.setText(totais[6]);
            qntTotalProd.setText(Integer.toString(Integer.parseInt(totais[4]) + Integer.parseInt(totais[5]) + Integer.parseInt(totais[6])));

            qntExaminadora.setText(totais[7]);
            qntJulgadora.setText(totais[8]);
            qntTotalBanca.setText(Integer.toString(Integer.parseInt(totais[7]) + Integer.parseInt(totais[8])));

            log.info(Main.recursos.getString("log.emitir.relatorio"));
        } catch (Exception ex) {
            log.warning(Main.recursos.getString("log.erro.relatorio"));
            Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEmitirRelatorioGeralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarRelGeral;
    private javax.swing.JButton btnCancelarRelPorProf;
    private javax.swing.JButton btnEmitirRelatorioGeral;
    private javax.swing.JButton btnEmitirRelatorioPorProf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel qntArtigos;
    private javax.swing.JLabel qntExaminadora;
    private javax.swing.JLabel qntJulgadora;
    private javax.swing.JLabel qntLivrosCap;
    private javax.swing.JLabel qntOriDoutorado;
    private javax.swing.JLabel qntOriEspecializacao;
    private javax.swing.JLabel qntOriGraduacao;
    private javax.swing.JLabel qntOriMestrado;
    private javax.swing.JLabel qntTotalBanca;
    private javax.swing.JLabel qntTotalOrientacao;
    private javax.swing.JLabel qntTotalProd;
    private javax.swing.JLabel qntTrab;
    private javax.swing.JTable relProfessor;
    // End of variables declaration//GEN-END:variables


}
